all:	object-view-demo package-view-demo packageindex

object-view-demo: object-view-demo.ts
	tsc object-view-demo.ts || /bin/true

package-view-demo:
	tsc package-view-demo.ts || /bin/true

packageindex: packageindex.ts
	tsc packageindex.ts || /bin/true
